<?php

namespace UA\UAplatformBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeRepository extends \Doctrine\ORM\EntityRepository
{

    public function display_user($id)
    {
        $user[]= array();
        $sql= $this->createQueryBuilder('a');
        $sql->where('a.id = :id');
        $sql->setParameter('id',$id);
        $sql->innerJoin('a.utilisateurs','u');
        $sql->addSelect('u');
        return $sql->getQuery()->getResult();

    }
}
