# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        UA\UserBundle\Entity\Utilisateur: sha512
    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern:      ^/
            anonymous:    true
            provider:   main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:       fos_user_security_logout
                target:     fos_user_security_login
            remember_me:
                secret:     %secret%

    access_control:
        - { path: /.*add$ ,role: ROLE_USER}
        - { path: /.*edit$ ,role: ROLE_USER}
        - { path: /.*delete$ ,role: ROLE_USER}
