services:
#    u_aplatform.example:
#        class: UA\UAplatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

  ua.room_service:
    class: UA\UAplatformBundle\Room\UARoom
    arguments:
      - '@gos_web_socket.websocket.client_manipulator'
      - '@doctrine.orm.entity_manager'
    tags:
      - { name: gos_web_socket.topic }